### ISSUE TITLE
Config: Multiple Keys, Same Value

### ISSUE THREAD

**Issue by calebsyring** [level12/env-config#13]
I wanted to set multiple keys to the same value from 1Pass in my config:
```yaml
profile:
  linode:
    TF_VAR_linode_api_token: 'op://private/linode api token/password'
    LINODE_CLI_TOKEN: 'op://private/linode api token/password'
```

This resulted in the `LINODE_CLI_TOKEN` var not being set at all even when the other var was set. Changing "private" to "Employee" for the `LINODE_CLI_TOKEN` 1Pass reference (making it a different reference to the same 1Pass item) caused everything to work properly. Some kind of caching problem?

While this seems to be a bug, it's also an opportunity to add a better/more semantic way to specify wanting multiple keys for the same value.
