### ISSUE TITLE
Support prompting for data

### ISSUE THREAD

**Issue by rsyring** [level12/env-config#14]
```yaml
profile:
  foo:
    SUDO_PASS: 'prompt://'
```

This would prompt the user for a value.  Might have to also think through how the shell integration would impact this.
