### ISSUE TITLE
Support plugins to customize functionality 

### ISSUE THREAD

**Issue by rsyring** [level12/env-config#15]
Resolving an environment variable is done through a [Resolver](https://github.com/level12/env-config/blob/6e313e05e6b705d81fc6ce8cb7e7224c11d072f9/src/env_config/core.py#L17) class.

We could add support for loading other Resolver classes through installed Python packages and/or module paths.  E.g.:

```yaml
resolvers:
  # This is a project name.  The resolver module path is read from the project's meta data.
  - env-config-bitwarden
  # This is a module path so resolvers can be loaded without installing a package.
  - myproj.libs.env_config:CustomResolver
profile:
  foo:
    # URL format isn't required, since Resolvers identify values they can resolver.  Obviously,
    # for this to work, env-config-bitwarden would need a resolver that can handle "bitwarden://"
    # paths.
    bar: 'bitwarden://work/myproj/bar'
    # And the custom resolver handles these
    baz: 'myproj://baz'
```

My guess is we'd use pluggy and can use pytest as an inspiration for how to integrate plugins.
